-- 자동생성: birds.json 전체(99종) 시드
-- 재실행 안전: 기존 birds 비우고 재삽입
TRUNCATE birds CASCADE;

INSERT INTO birds (name_ko, name_sci, type, regions, season_start, season_end, rarity, description, silhouette_url) VALUES
('참새', 'Passer montanus', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '한국 전역에 서식하는 가장 흔한 텃새. 갈색과 흰색 줄무늬가 특징이며 인가 주변에서 주로 생활한다.', '/silhouette.svg'),
('까치', 'Pica serica', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시'], NULL, NULL, 'common', '한국의 국조(國鳥). 흑백 대비가 뚜렷하며 나무 꼭대기에 둥지를 틀고 사람 가까이 산다.', '/silhouette.svg'),
('까마귀', 'Corvus corone', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '전신이 광택 있는 검은색인 대형 조류. 지능이 높고 사회성이 강하다.', '/silhouette.svg'),
('멧비둘기', 'Streptopelia orientalis', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '산과 도시 공원 모두에서 볼 수 있는 흔한 텃새. 목에 줄무늬 무늬가 있다.', '/silhouette.svg'),
('박새', 'Parus major', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '가슴의 검은 줄무늬가 특징인 작은 텃새. 나무 구멍에 둥지를 트는 산림성 조류.', '/silhouette.svg'),
('곤줄박이', 'Sittiparus varius', 'resident', ARRAY['서울특별시','경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '주황색 배와 흑백 머리가 인상적인 산림성 텃새. 도토리를 저장하는 습성이 있다.', '/silhouette.svg'),
('오목눈이', 'Aegithalos caudatus', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '긴 꼬리와 둥그런 몸체가 특징인 소형 텃새. 겨울에 무리 지어 다닌다.', '/silhouette.svg'),
('동고비', 'Sitta europaea', 'resident', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '나무 줄기를 거꾸로 내려올 수 있는 특이한 능력을 가진 소형 조류.', '/silhouette.svg'),
('딱새', 'Phoenicurus auroreus', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '수컷은 주황색 배와 검은 얼굴이 화려하다. 꼬리를 아래위로 흔드는 습성이 있다.', '/silhouette.svg'),
('직박구리', 'Hypsipetes amaurotis', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '귀 부분의 갈색 무늬와 날카로운 울음소리가 특징. 도시와 산림 경계에서 흔히 보인다.', '/silhouette.svg'),
('물까치', 'Cyanopica cyanus', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '하늘색 날개와 긴 꼬리가 아름다운 조류. 하천 주변 나무에서 무리 지어 서식한다.', '/silhouette.svg'),
('어치', 'Garrulus glandarius', 'resident', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '날개의 파란 무늬가 인상적인 까마귀과 조류. 도토리를 저장하는 숲속 텃새.', '/silhouette.svg'),
('굴뚝새', 'Troglodytes troglodytes', 'resident', ARRAY['강원도','경기도','충청북도','경상북도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '한국에서 가장 작은 새 중 하나. 꼬리를 세우고 큰 목소리로 지저귀는 특성이 있다.', '/silhouette.svg'),
('붉은머리오목눈이', 'Sinosuthora webbiana', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '붉은 갈색 머리와 줄무늬 몸통이 특징. 갈대밭이나 덤불에서 무리 생활을 한다.', '/silhouette.svg'),
('노랑턱멧새', 'Emberiza elegans', 'resident', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '노란 목과 검은 눈 무늬가 선명한 멧새. 산기슭 덤불에서 번식한다.', '/silhouette.svg'),
('황조롱이', 'Falco tinnunculus', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '도심 빌딩에서도 번식하는 작은 매. 제자리비행(호버링)으로 먹이를 찾는 습성이 있다.', '/silhouette.svg'),
('새홀리기', 'Falco subbuteo', 'migratory', ARRAY['경기도','강원도','충청북도','경상북도','전라북도'], 5, 9, 'common', '빠른 비행 속도로 잠자리와 소형 조류를 잡아먹는 소형 매. 여름 철새.', '/silhouette.svg'),
('붉은배새매', 'Accipiter soloensis', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 4, 9, 'common', '가슴의 붉은 줄무늬가 특징인 소형 매. 논과 밭 주변 수림에서 번식한다.', '/silhouette.svg'),
('참매', 'Accipiter gentilis', 'resident', ARRAY['강원도','경기도','충청북도','경상북도','전라북도'], NULL, NULL, 'endangered_2', '강력한 사냥 능력을 가진 대형 맹금류. 울창한 산림에서 서식하며 개체 수가 적다.', '/silhouette.svg'),
('흰꼬리수리', 'Haliaeetus albicilla', 'migratory', ARRAY['경기도','인천광역시','강원도','충청남도','전라북도','전라남도','경상남도'], 10, 3, 'endangered_1', '날개 폭이 2m를 넘는 대형 독수리. 흰 꼬리가 특징이며 겨울철 강과 호수에서 월동한다.', '/silhouette.svg'),
('독수리', 'Aegypius monachus', 'migratory', ARRAY['경기도','강원도','충청남도','경상남도','전라남도'], 10, 3, 'endangered_2', '날개 폭 3m의 초대형 맹금류. 죽은 동물을 먹는 청소부 역할을 하며 겨울에 도래한다.', '/silhouette.svg'),
('두루미', 'Grus japonensis', 'migratory', ARRAY['경기도','강원도','경상북도'], 11, 3, 'endangered_1', '한국의 대표적인 겨울 철새. 붉은 이마와 흑백 몸통이 특징이며 철원 지역에서 월동한다.', '/silhouette.svg'),
('재두루미', 'Grus vipio', 'migratory', ARRAY['경기도','강원도','경상북도','전라북도'], 10, 3, 'endangered_2', '두루미보다 작으며 얼굴에 붉은 피부가 노출된 대형 조류. 철원과 순천만에서 월동.', '/silhouette.svg'),
('흑두루미', 'Grus monacha', 'migratory', ARRAY['전라남도','경상남도'], 10, 3, 'endangered_2', '흑색 몸통에 흰 목이 대비되는 중형 두루미. 순천만 갈대밭에서 월동하는 것으로 유명.', '/silhouette.svg'),
('저어새', 'Platalea minor', 'migratory', ARRAY['인천광역시','경기도','전라남도','경상남도','제주도'], 3, 10, 'endangered_1', '주걱 모양 부리가 특징인 국제적 멸종위기종. 인천 무인도에서 번식하는 세계적 희귀종.', '/silhouette.svg'),
('노랑부리저어새', 'Platalea leucorodia', 'migratory', ARRAY['인천광역시','전라남도','경상남도'], 10, 3, 'endangered_2', '저어새와 유사하지만 더 크고 부리 끝이 노란색. 겨울 철새로 서해안에서 월동.', '/silhouette.svg'),
('황새', 'Ciconia boyciana', 'migratory', ARRAY['충청남도','경기도','전라북도','전라남도'], 10, 3, 'endangered_1', '날개 폭 2m의 대형 조류. 과거 한국에서 번식했으나 현재는 겨울 철새로만 도래하는 극희귀종.', '/silhouette.svg'),
('큰기러기', 'Anser fabalis', 'migratory', ARRAY['경기도','인천광역시','강원도','충청남도','전라북도','전라남도','경상남도'], 10, 3, 'common', '대형 기러기로 겨울철 논밭과 습지에서 무리 지어 월동. ''V''자 편대 비행이 인상적.', '/silhouette.svg'),
('흰기러기', 'Anser caerulescens', 'migratory', ARRAY['인천광역시','경기도','전라남도'], 11, 2, 'common', '전신이 흰색인 기러기로 드물게 한국을 찾는 겨울 철새.', '/silhouette.svg'),
('오리', 'Anas platyrhynchos', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 10, 3, 'common', '수컷의 초록 머리가 특징인 대표적인 겨울 철새 오리. 도심 하천에서도 흔히 관찰된다.', '/silhouette.svg'),
('청둥오리', 'Anas platyrhynchos', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 10, 3, 'common', '가장 흔한 겨울 철새 오리. 수컷의 광택 있는 초록 머리가 특징이다.', '/silhouette.svg'),
('원앙', 'Aix galericulata', 'resident', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '수컷의 화려한 깃털이 세계적으로 유명한 조류. 계곡 주변 나무 구멍에 둥지를 튼다.', '/silhouette.svg'),
('고방오리', 'Anas acuta', 'migratory', ARRAY['경기도','인천광역시','충청남도','전라북도','전라남도','경상남도'], 10, 3, 'common', '긴 꼬리가 특징인 날씬한 오리. 서해안 갯벌과 논에서 겨울을 보낸다.', '/silhouette.svg'),
('흰뺨검둥오리', 'Anas zonorhyncha', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '뺨의 흰 무늬가 특징인 한국 고유 계통 오리. 도심 하천과 논에서 흔히 서식한다.', '/silhouette.svg'),
('논병아리', 'Tachybaptus ruficollis', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '가장 작은 논병아리류. 잠수 능력이 뛰어나며 연못과 저수지에서 서식한다.', '/silhouette.svg'),
('뿔논병아리', 'Podiceps cristatus', 'migratory', ARRAY['경기도','인천광역시','충청남도','전라북도','전라남도','경상남도'], 10, 3, 'common', '머리의 뿔 모양 장식 깃털이 인상적인 중형 논병아리. 겨울 바다와 큰 호수에서 월동.', '/silhouette.svg'),
('가마우지', 'Phalacrocorax carbo', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청남도','전라북도','전라남도','경상남도','제주도'], 10, 3, 'common', '날개를 펴고 말리는 독특한 행동이 특징인 대형 수조류. 강과 바다 모두에서 관찰된다.', '/silhouette.svg'),
('민물가마우지', 'Phalacrocorax niger', 'resident', ARRAY['경기도','강원도','충청북도','경상북도','전라북도','전라남도'], NULL, NULL, 'common', '내륙 하천과 저수지에서 번식하는 가마우지류. 군집 번식지를 형성한다.', '/silhouette.svg'),
('왜가리', 'Ardea cinerea', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','경상북도','경상남도','대구광역시','부산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '날개 폭 2m의 대형 왜가리. 강가와 논에서 긴 다리로 서서 물고기를 낚아채는 대형 텃새.', '/silhouette.svg'),
('대백로', 'Ardea alba', 'migratory', ARRAY['경기도','인천광역시','충청남도','전라북도','전라남도','경상남도','제주도'], 4, 10, 'common', '전신이 흰색인 대형 백로. 번식기에 아름다운 장식 깃털(에그렛)이 발달한다.', '/silhouette.svg'),
('중백로', 'Ardea intermedia', 'migratory', ARRAY['경기도','충청남도','전라북도','전라남도','경상남도'], 4, 9, 'common', '대백로와 쇠백로의 중간 크기 백로. 논과 습지에서 여름을 보낸다.', '/silhouette.svg'),
('쇠백로', 'Egretta garzetta', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청남도','전라북도','전라남도','경상남도','제주도'], 4, 10, 'common', '작은 백로류로 노란 발가락이 특징. 논과 하천에서 흔히 볼 수 있는 여름 철새.', '/silhouette.svg'),
('황로', 'Bubulcus ibis', 'migratory', ARRAY['충청남도','전라북도','전라남도','경상남도','제주도'], 4, 9, 'common', '소나 말 옆에 붙어 다니며 먹이를 찾는 백로. 번식기에 머리와 가슴이 황갈색으로 변한다.', '/silhouette.svg'),
('해오라기', 'Nycticorax nycticorax', 'migratory', ARRAY['서울특별시','경기도','인천광역시','충청남도','전라북도','전라남도','경상남도'], 4, 10, 'common', '야행성 왜가리류로 주로 밤에 활동. 흑백의 대비가 선명하고 붉은 눈이 특징.', '/silhouette.svg'),
('흰해오라기', 'Egretta eulophotes', 'migratory', ARRAY['인천광역시','전라남도','경상남도'], 4, 9, 'endangered_1', '노란 부리와 흰 몸이 특징인 멸종위기종 백로. 서해안 무인도에서 소수가 번식한다.', '/silhouette.svg'),
('물총새', 'Alcedo atthis', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '청록색 등과 주황색 배의 보석 같은 소형 조류. 맑은 하천에서 물고기를 사냥한다.', '/silhouette.svg'),
('후투티', 'Upupa epops', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], 4, 9, 'common', '화려한 부채 모양 관우와 긴 굽은 부리가 특징. 나무 구멍이나 돌담에 둥지를 튼다.', '/silhouette.svg'),
('파랑새', 'Eurystomus orientalis', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 5, 9, 'common', '온몸이 파랗고 붉은 부리가 대비되는 아름다운 여름 철새. 활엽수림에서 번식한다.', '/silhouette.svg'),
('뻐꾸기', 'Cuculus canorus', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], 4, 9, 'common', '''뻐꾹'' 소리로 여름을 알리는 철새. 다른 새의 둥지에 탁란하는 습성이 있다.', '/silhouette.svg'),
('두견이', 'Cuculus poliocephalus', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], 5, 8, 'common', '산에서 ''두견 두견'' 우는 소형 뻐꾸기류. 귀촉도라는 별명으로 한국 시가에 자주 등장한다.', '/silhouette.svg'),
('솔개', 'Milvus migrans', 'migratory', ARRAY['경기도','인천광역시','강원도','경상남도','전라남도','제주도'], 3, 4, 'endangered_2', '갈라진 꼬리가 특징인 중형 맹금류. 이동 시기에 무리 지어 상승기류를 타는 모습이 장관이다.', '/silhouette.svg'),
('말똥가리', 'Buteo buteo', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 10, 3, 'common', '전봇대 위에 앉아 있는 모습을 쉽게 볼 수 있는 중형 맹금류. 쥐를 주식으로 한다.', '/silhouette.svg'),
('새매', 'Accipiter nisus', 'resident', ARRAY['경기도','강원도','충청북도','경상북도','전라북도'], NULL, NULL, 'common', '소형 조류를 전문으로 사냥하는 날쌘 맹금류. 숲 속을 빠르게 누비며 먹이를 추격한다.', '/silhouette.svg'),
('붉은배새', 'Luscinia calliope', 'migratory', ARRAY['경기도','강원도','충청북도','경상북도'], 5, 9, 'common', '수컷의 붉은 목이 아름다운 소형 조류. 높은 산 침엽수림에서 번식한다.', '/silhouette.svg'),
('흰눈썹황금새', 'Ficedula zanthopygia', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 4, 9, 'common', '노란 가슴과 흰 눈썹이 선명한 소형 여름 철새. 산지 활엽수림에서 번식한다.', '/silhouette.svg'),
('큰유리새', 'Cyanoptila cyanomelana', 'migratory', ARRAY['경기도','강원도','충청북도','경상북도','전라북도'], 4, 9, 'common', '수컷의 청람색 등이 아름다운 대형 딱새류. 계곡 주변 울창한 숲에서 번식한다.', '/silhouette.svg'),
('제비', 'Hirundo rustica', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','경상북도','경상남도','대구광역시','부산광역시','전라북도','전라남도','광주광역시','제주도'], 4, 9, 'common', '한국의 대표적인 여름 철새. 인가 처마 밑에 진흙 둥지를 짓고 새끼를 기른다.', '/silhouette.svg'),
('칼새', 'Apus pacificus', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청남도','경상남도','전라남도','제주도'], 4, 8, 'common', '날개 모양이 낫처럼 생긴 고속 비행 조류. 거의 땅에 내려앉지 않고 하늘에서만 생활한다.', '/silhouette.svg'),
('쏙독새', 'Caprimulgus jotaka', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 5, 9, 'common', '야행성 조류로 보호색이 뛰어나다. 땅바닥에 의태하여 낮에는 잠을 자고 밤에 활동한다.', '/silhouette.svg'),
('소쩍새', 'Otus sunia', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], 4, 9, 'common', '한국에서 가장 작은 올빼미류. ''소쩍 소쩍'' 우는 소리로 밤을 알리는 여름 철새.', '/silhouette.svg'),
('올빼미', 'Strix aluco', 'resident', ARRAY['경기도','강원도','충청북도','경상북도','전라북도'], NULL, NULL, 'endangered_2', '한국의 대표적인 야행성 맹금류. 나무 구멍에서 서식하며 쥐와 소형 포유류를 사냥한다.', '/silhouette.svg'),
('수리부엉이', 'Bubo bubo', 'resident', ARRAY['강원도','경기도','충청북도','경상북도','전라북도'], NULL, NULL, 'endangered_2', '한국 최대의 올빼미류. 귀 모양의 깃털(귀깃)과 주황색 눈이 특징인 대형 야행성 맹금류.', '/silhouette.svg'),
('쇠부엉이', 'Asio flammeus', 'migratory', ARRAY['경기도','인천광역시','강원도','충청남도','전라북도','전라남도'], 10, 3, 'common', '낮에도 활동하는 올빼미류. 초원과 갯벌 주변에서 겨울을 보내며 들쥐를 사냥한다.', '/silhouette.svg'),
('쇠딱다구리', 'Picoides kizuki', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '한국에서 가장 작은 딱다구리. 죽은 나무 줄기를 빠르게 쪼아 곤충 유충을 찾아먹는다.', '/silhouette.svg'),
('오색딱다구리', 'Dendrocopos major', 'resident', ARRAY['서울특별시','경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '흑백 무늬에 빨간 뒤통수가 선명한 중형 딱다구리. 공원과 산림 모두에서 관찰된다.', '/silhouette.svg'),
('청딱다구리', 'Picus canus', 'resident', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '녹색 몸통과 빨간 머리의 대형 딱다구리. 땅에 내려와 개미를 잡아먹기도 한다.', '/silhouette.svg'),
('크낙새', 'Dryocopus javensis', 'resident', ARRAY['경기도'], NULL, NULL, 'endangered_1', '한국 최대의 딱다구리로 현재 극소수만 경기도 광릉 지역에 서식하는 국제적 멸종위기종.', '/silhouette.svg'),
('꾀꼬리', 'Oriolus chinensis', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], 5, 9, 'common', '샛노란 몸과 검은 날개의 대비가 아름다운 여름 철새. 맑고 낭랑한 울음소리가 특징.', '/silhouette.svg'),
('때까치', 'Lanius bucephalus', 'resident', ARRAY['서울특별시','경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], NULL, NULL, 'common', '가시나무에 잡은 먹이를 꽂아두는 독특한 습성이 있는 중형 조류. ''도살자 새''라고도 불린다.', '/silhouette.svg'),
('노랑할미새', 'Motacilla cinerea', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '노란 배와 긴 꼬리가 특징인 할미새류. 맑은 계류 옆에서 서식하며 꼬리를 위아래로 흔든다.', '/silhouette.svg'),
('백할미새', 'Motacilla alba', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '흑백의 대비가 선명한 할미새. 인가 근처와 하천변에서 흔히 볼 수 있는 텃새.', '/silhouette.svg'),
('힝둥새', 'Anthus hodgsoni', 'migratory', ARRAY['경기도','강원도','충청북도','경상북도','전라북도'], 4, 9, 'common', '고산 침엽수림에서 번식하는 소형 멧새류. 나무 꼭대기에서 노래하는 여름 철새.', '/silhouette.svg'),
('멧도요', 'Scolopax rusticola', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 3, 4, 'common', '낙엽 속 보호색이 완벽한 중형 도요류. 긴 부리로 습지 흙 속 지렁이를 찾아먹는다.', '/silhouette.svg'),
('중부리도요', 'Numenius phaeopus', 'migratory', ARRAY['인천광역시','경기도','충청남도','전라북도','전라남도','경상남도','제주도'], 4, 5, 'common', '아래로 굽은 긴 부리가 특징인 대형 도요. 이동 시기에 갯벌에서 대규모 무리를 이룬다.', '/silhouette.svg'),
('알락꼬리마도요', 'Numenius madagascariensis', 'migratory', ARRAY['인천광역시','충청남도','전라북도','전라남도','경상남도'], 4, 5, 'endangered_1', '도요류 중 가장 긴 부리를 가진 대형 종. 서해안 갯벌을 이용하는 국제 멸종위기종.', '/silhouette.svg'),
('민물도요', 'Calidris alpina', 'migratory', ARRAY['인천광역시','경기도','충청남도','전라남도','경상남도'], 8, 10, 'common', '서해안 갯벌에서 수천 마리가 무리 지어 먹이를 찾는 소형 도요. 이동 시 장관을 연출한다.', '/silhouette.svg'),
('흰물떼새', 'Charadrius alexandrinus', 'resident', ARRAY['인천광역시','경기도','충청남도','전라남도','경상남도','제주도'], NULL, NULL, 'common', '해변 모래밭에서 번식하는 작은 물떼새. 모래색 보호색 덕분에 발견하기 어렵다.', '/silhouette.svg'),
('검은머리물떼새', 'Haematopus ostralegus', 'resident', ARRAY['인천광역시','충청남도','전라남도','경상남도'], NULL, NULL, 'endangered_2', '주황색 부리와 흑백 몸통이 뚜렷한 중형 조류. 갯벌에서 조개와 굴을 쪼아 먹는다.', '/silhouette.svg'),
('괭이갈매기', 'Larus crassirostris', 'resident', ARRAY['인천광역시','경기도','충청남도','전라남도','경상남도','부산광역시','제주도'], NULL, NULL, 'common', '한국 연안에서 가장 흔한 갈매기. 눈 주변의 붉은 테두리가 특징이며 항구에서 쉽게 볼 수 있다.', '/silhouette.svg'),
('재갈매기', 'Larus argentatus', 'migratory', ARRAY['인천광역시','경기도','충청남도','전라남도','경상남도','부산광역시','제주도'], 10, 3, 'common', '대형 갈매기로 분홍색 다리가 특징. 항구와 연안에서 겨울을 보내는 흔한 철새.', '/silhouette.svg'),
('제비갈매기', 'Sterna hirundo', 'migratory', ARRAY['인천광역시','충청남도','전라남도','경상남도'], 4, 9, 'common', '갈라진 꼬리와 빠른 비행이 특징인 소형 갈매기류. 무인도에서 번식한다.', '/silhouette.svg'),
('쇠제비갈매기', 'Sternula albifrons', 'migratory', ARRAY['인천광역시','충청남도','전라남도','경상남도'], 4, 9, 'endangered_2', '노란 부리에 검은 끝이 특징인 소형 갈매기류. 모래사장에서 번식하며 개체 수가 감소 중.', '/silhouette.svg'),
('바다오리', 'Uria aalge', 'migratory', ARRAY['강원도','경상북도','경상남도','부산광역시'], 11, 2, 'common', '수직으로 서서 펭귄처럼 걷는 대형 바닷새. 동해안 바다에서 소수가 월동한다.', '/silhouette.svg'),
('슴새', 'Calonectris leucomelas', 'migratory', ARRAY['강원도','경상북도','경상남도','전라남도','제주도'], 4, 10, 'common', '외양성 바닷새로 파도 위를 활강하는 모습이 인상적. 무인도 암벽에서 집단 번식한다.', '/silhouette.svg'),
('바다제비', 'Oceanodroma monorhis', 'migratory', ARRAY['전라남도','경상남도','제주도'], 5, 9, 'endangered_2', '손바닥만한 소형 바닷새. 밤에만 번식지에 출입하며 무인도 땅속 굴에 알을 낳는다.', '/silhouette.svg'),
('검은목논병아리', 'Podiceps nigricollis', 'migratory', ARRAY['인천광역시','경기도','전라남도','경상남도'], 10, 3, 'common', '번식기에 눈 뒤에 황금색 장식 깃털이 발달하는 소형 논병아리. 겨울 바다에서 월동.', '/silhouette.svg'),
('두꺼비새', 'Saxicola maurus', 'migratory', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 4, 9, 'common', '풀밭과 경작지 주변에서 번식하는 소형 조류. 전신주나 나뭇가지 꼭대기에 앉아 주변을 경계한다.', '/silhouette.svg'),
('개개비', 'Acrocephalus orientalis', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 5, 9, 'common', '갈대밭에서 ''개개개개'' 시끄럽게 우는 소형 조류. 갈대 줄기를 타고 오르내리며 곤충을 잡는다.', '/silhouette.svg'),
('휘파람새', 'Horornis diphone', 'resident', ARRAY['경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도','제주도'], NULL, NULL, 'common', '''호오 케캬오'' 하는 맑은 노래로 유명한 소형 새. 산지 덤불에서 서식하며 모습을 잘 드러내지 않는다.', '/silhouette.svg'),
('솔새', 'Phylloscopus borealis', 'migratory', ARRAY['경기도','강원도','충청북도','경상북도','전라북도'], 5, 9, 'common', '눈썹선이 뚜렷한 소형 개개비류. 침엽수림 수관부에서 활발히 활동하는 여름 철새.', '/silhouette.svg'),
('검은이마직박구리', 'Pycnonotus sinensis', 'resident', ARRAY['제주도','전라남도'], NULL, NULL, 'common', '검은 이마와 흰 뺨이 대비되는 남방계 텃새. 제주도에서 주로 관찰된다.', '/silhouette.svg'),
('팔색조', 'Pitta nympha', 'migratory', ARRAY['전라남도','경상남도','제주도'], 5, 9, 'endangered_2', '8가지 색이 어우러진 세계에서 가장 아름다운 새 중 하나. 제주도 등 남부 산림에서 번식.', '/silhouette.svg'),
('붉은가슴도요', 'Calidris canutus', 'migratory', ARRAY['인천광역시','충청남도','전라남도'], 4, 5, 'endangered_2', '번식기에 붉은 가슴이 발달하는 중형 도요. 서해안 갯벌을 중간 기착지로 이용하는 국제 희귀종.', '/silhouette.svg'),
('검은머리갈매기', 'Chroicocephalus saundersi', 'migratory', ARRAY['인천광역시','충청남도','전라남도'], 3, 9, 'endangered_2', '검은 두건 모양 머리가 특징인 소형 갈매기. 서해안 무인도에서 소수가 번식하는 희귀 조류.', '/silhouette.svg'),
('노랑발도요', 'Heteroscelus brevipes', 'migratory', ARRAY['인천광역시','충청남도','전라남도','경상남도','제주도'], 4, 5, 'common', '노란 발이 특징인 중형 도요. 갯벌과 암초 해안에서 이동 시기에 관찰된다.', '/silhouette.svg'),
('세가락도요', 'Calidris alba', 'migratory', ARRAY['인천광역시','충청남도','전라남도','경상남도'], 8, 10, 'common', '파도를 따라 모래해변을 달리는 특이한 행동을 하는 소형 도요. 발가락이 3개뿐이다.', '/silhouette.svg'),
('흰눈썹뜸부기', 'Amaurornis phoenicurus', 'migratory', ARRAY['제주도','전라남도','경상남도'], 5, 9, 'common', '흰 얼굴과 갈색 옆구리가 대비되는 중형 뜸부기류. 남부 습지에서 번식하는 여름 철새.', '/silhouette.svg'),
('쇠뜸부기', 'Porzana pusilla', 'migratory', ARRAY['경기도','충청남도','전라북도','전라남도'], 4, 9, 'common', '갈대밭과 습지 식물 사이를 은밀하게 다니는 소형 뜸부기. 소리로 존재를 알린다.', '/silhouette.svg'),
('도요물떼새', 'Charadrius dubius', 'migratory', ARRAY['서울특별시','경기도','강원도','충청북도','충청남도','경상북도','경상남도','전라북도','전라남도'], 4, 9, 'common', '노란 눈테가 선명한 소형 물떼새. 하천 모래밭과 자갈밭에서 번식한다.', '/silhouette.svg'),
('집비둘기', 'Columba livia', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '도심 어디서나 볼 수 있는 가장 흔한 새. 회색 몸통에 목 부분의 무지개빛 광택이 특징이다.', '/silhouette.svg'),
('꿩', 'Phasianus colchicus', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '산과 들판에 서식하는 대형 텃새. 수컷은 붉은 얼굴과 화려한 깃털, 암컷은 갈색 보호색을 띤다.', '/silhouette.svg'),
('방울새', 'Chloris sinica', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '노란 날개띠가 특징인 텃새. 씨앗을 즐겨 먹으며 공원과 산림 가장자리에서 흔히 볼 수 있다.', '/silhouette.svg'),
('개똥지빠귀', 'Turdus eunomus', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], 10, 4, 'common', '가을과 겨울에 무리 지어 도래하는 흔한 겨울 철새. 가슴의 갈색 반점이 특징이다.', '/silhouette.svg'),
('멧새', 'Emberiza cioides', 'resident', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], NULL, NULL, 'common', '산과 들판에 서식하는 텃새. 수컷은 밤색 머리와 흰 눈썹선이 특징이다.', '/silhouette.svg'),
('흰배지빠귀', 'Turdus pallidus', 'migratory', ARRAY['서울특별시','경기도','인천광역시','강원도','충청북도','충청남도','대전광역시','세종특별자치시','경상북도','경상남도','대구광역시','부산광역시','울산광역시','전라북도','전라남도','광주광역시','제주도'], 10, 4, 'common', '흰 배와 주황색 옆구리가 특징인 겨울 철새. 낙엽 쌓인 숲 바닥을 뒤지며 먹이를 찾는다.', '/silhouette.svg');
